### ISSUE TITLE
Branch management strategy after 3.1.0 release

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/discuss#11]
We follow [semver2](http://semver.org/spec/v2.0.0.html), then we need to consider how to maintain code for patch release like 3.1.x, and major/minor update such as 3.2.0 and 4.0.0. I'm not sure that we have motivation to release 3.2.0 or not (we have [milestone only for 4.0.0](https://github.com/spotbugs/spotbugs/milestone/2)), though.

In my experience, it is natural to use `master` for major update, and `release-3.1` branch for patch. Any idea?

**Comment by iloveeclipse** [comment]
Yes, I think we can maintain one 3.1.x patch release without API changes and a playground on master will be targeting 4.0.
