### ISSUE TITLE
Question about license

### ISSUE THREAD

**Issue by tliter** [spotbugs/discuss#117]
I'm not sure if this is the right place to ask such questions, but i'll try.
I want to know few things about the license. I'm not sure if I understood it correctly. Can i use SpotBugs as help(bugcheck) to develop a commercial game for free? Next question: from what I understood i must make source open only  in the case when i'm extending source code of SpotBugs. Not when i'm using it as help to find bugs in software? Are there any other restrictions I should be aware of?

Greetings tliter.

**Comment by henrik242** [comment]
Spotbugs in under the GNU Lesser General Public License v2.1.  This licence is primarily used for software libraries, and requires that derived works be licensed under the same license, but works that only link to it do not fall under this restriction. 

So the answer is: You can freely use Spotbugs til help your commercial game for free.  More info at https://tldrlegal.com/license/gnu-lesser-general-public-license-v2.1-(lgpl-2.1)

**Comment by tliter** [comment]
What about source disclose? If i'm only using it for bug check in  game development. Am I forced to open the source code of my game? Maybe this question sounds silly, but I'm not a lawyer.

**Comment by henrik242** [comment]
> Am I forced to open the source code of my game?

No.

**Comment by tliter** [comment]
thanks for help.

**Comment by henrik242** [comment]
np
