### ISSUE TITLE
When does idea spotbugs plugin support spotbugs version 4.6.0?

### ISSUE THREAD

**Issue by gaiwey** [spotbugs/discuss#118]
Currently, the spotbugs version in idea plugins is 4.4.2. Is there a plan for an updated version recently?

**Comment by lasselindqvist** [comment]
You should probably ask this in https://github.com/JetBrains/spotbugs-intellij-plugin/issues
JetBrains seems to be the maintainer for that.

**Comment by KengoTODA** [comment]
Yes better to ask JetBrains. I will close this issue so please open another one in their repository.
