### ISSUE TITLE
Privacy and Data Protection policy Plug-in 

### ISSUE THREAD

**Issue by nidhiyanandh** [spotbugs/discuss#122]
Hi team,

I want know the spotbugs plugin policy and data protection. Can someone help me over here 

Thanks

**Comment by iloveeclipse** [comment]
What do you mean by:
1) "plugin policy"?
2) "data protection"?

**Comment by nidhiyanandh** [comment]
Hi iloveeclipse,
Thanks 
I want some info regarding the spotbug eclipse plug-in , ideas intelli plug-in ; is collecting any user information or code analysis related data?
If it's collecting how the user/code realted analysis data managed and what are the standards are followed?

I hope,  you got

**Comment by iloveeclipse** [comment]
> ideas intelli plug-in

Is NOT provided by this project.

> eclipse plug-in is collecting any user information or code analysis related data?

Please define "collecting", "any" and "related" terms.

The plugin in Eclipse runs Spotbugs and saves the analysis result in the workspace / creates markers on code. That is "collecting" of "any" "related" data.

What you probably want to ask : do we share the analysis data/information with any anyone else **except** current user?

No.

**Comment by nidhiyanandh** [comment]
Hi @iloveeclipse ,

Thanks for the input,  

 Basically I want to understand. Is code analysis data , user data or  anonymous data ; have been collected for part of plug-in feature improvements?. 

If yes, Collected data's how its maintained and managed.

As per previous input those data's not collected and not shared.  is i am correct?; thanks again!
