### ISSUE TITLE
Sportbugs as plugin for Jenkins pipeline

### ISSUE THREAD

**Issue by AltranManatree** [spotbugs/discuss#13]
I want to use spotbugs in jenkins Pipeline, but I cannot find the plugin for it as it is for findbugs.
And how can I use spotbugs as a standalone tool?

**Comment by iloveeclipse** [comment]
To use spotbugs in Jenkins you can just continue to use findbugs plugin, then the output format isn't changed.
If you build with maven, you can just switch in your pom file which tool you use, see for example: https://git.eclipse.org/r/#/c/101312/

For the standalone please consider to read the manual: http://spotbugs.readthedocs.io/en/latest/running.html

**Comment by iloveeclipse** [comment]
See also https://issues.jenkins-ci.org/browse/JENKINS-46975

**Comment by AltranManatree** [comment]
Thank you for your answer. 
However, concerning the standalone, I am getting the following error : 

"One or more required BCEL classes were missing. Ensure that bcel.jar is placed at the same directory with spotbugs.jar"

I have already checked the following : 
https://github.com/spotbugs/spotbugs/issues/405

**Comment by iloveeclipse** [comment]
Please use the RC5 build. RC6 command line is broken, but next RC will have the fix.

**Comment by AltranManatree** [comment]
Ok thank for your response.

**Comment by KengoTODA** [comment]
Let me close this issue. Feel free to reopen.

**Comment by jayeff** [comment]
An information for anyone landing here: 
> The FindBugs plug-in reached end-of-life. It is not supported anymore - all functionality has been integrated into the Warning Plugin.
> Source: https://wiki.jenkins.io/display/JENKINS/FindBugs+Plugin

Link to Warnings Plugin: https://wiki.jenkins.io/display/JENKINS/Warnings+Plugin

**Comment by rhamedy** [comment]
> An information for anyone landing here:
> 
> > The FindBugs plug-in reached end-of-life. It is not supported anymore - all functionality has been integrated into the Warning Plugin.
> > Source: https://wiki.jenkins.io/display/JENKINS/FindBugs+Plugin
> 
> Link to Warnings Plugin: https://wiki.jenkins.io/display/JENKINS/Warnings+Plugin

The `Warnings Plugin` reached end of life and there is `Warnings Next Generation Plugin` https://wiki.jenkins.io/display/JENKINS/Warnings+Next+Generation+Plugin

**Comment by uhafner** [comment]
Since the Jenkins wiki is also reaching end-of-life, the correct link is https://github.com/jenkinsci/warnings-ng-plugin.
