### ISSUE TITLE
FYI: SpotBugs will undergo IP check at Eclipse Foundation

### ISSUE THREAD

**Issue by sewe** [spotbugs/discuss#14]
I am writing this with both my Eclipse and SpotBugs committer hats on: We at [Eclipse Code Recommenders](https://www.eclipse.org/recommenders/) are currently considering building a set of SpotBugs detectors based on machine-learning (just like Code Recommenders is ML-based code-completion).

To that end, we need to initiate a so-called IP check of the SpotBugs codebase during which its provenance will be checked by the Eclipse legal team. Also, there is the issue of LGPL/EPL compatibility.

If you are interested, you can follow the discussion with the legal team in [CQs 14164](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=14164) and [14163](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=14163) (Eclipse committer login required), but I will report any findings here.

**Comment by iloveeclipse** [comment]
Thanks. Good to know.

**Comment by KengoTODA** [comment]
It seems that [the project is archived](https://www.eclipse.org/projects/archives.php).
