### ISSUE TITLE
FYI: Quiet period after RC7

### ISSUE THREAD

**Issue by iloveeclipse** [spotbugs/discuss#15]
Hi all,

We plan to release RC7 shortly and I would like to propose an integration stop for a week, to have a chance to release 3.1.0 final on next weekend, if RC7 would be OK.

Please do not merge PR's except bugfixes for regressions reported against RC7.

THANKS!

**Comment by KengoTODA** [comment]
Then could you consider to merge existing PRs before releasing RC7? Especially:

* https://github.com/spotbugs/spotbugs/pull/395
* https://github.com/spotbugs/spotbugs/pull/425
* https://github.com/spotbugs/spotbugs/pull/448
* https://github.com/spotbugs/spotbugs/pull/449

I think 435 and 447 are not urgent.  
I'm not sure 449 is necessary or not, we have no test to ensure that change is valid.

**Comment by henrik242** [comment]
They looked good, so I went ahead and merged them all :)

**Comment by iloveeclipse** [comment]
Thanks @henrik242 and @KengoTODA!

So it looks like we have the RC7 build. 

Please spead the word about it - would be nice to have some feedback before this will be declared to a final 3.1.0.

I propose to wait a week and release 3.1.0 on coming weekend, if no regressions would be reported. Any objections?
