### ISSUE TITLE
Spotbugs Eclipse Plugin

### ISSUE THREAD

**Issue by mttjj** [spotbugs/discuss#2]
Is there any documentation for getting the eclipse plugin set up for development? I want to try my hand at enhancing the plugin a bit but am not sure how to get started so the code is all compiled and working in Eclipse. There may be a document out there already; I just didn't find anything.

Thanks.

**Comment by mttjj** [comment]
Of course. As soon as I make this post, I found it.

Tutorials here: https://github.com/spotbugs/spotbugs/tree/master/eclipsePlugin/doc

**Comment by KengoTODA** [comment]
Latest document is [here](http://spotbugs.readthedocs.io/en/latest/eclipse.html), please refer this page too.
