### ISSUE TITLE
spotbugs-maven-plugin 3.1.0 final release?

### ISSUE THREAD

**Issue by bshannon** [spotbugs/discuss#23]
(Is there really no actual mailing list?  Am I supposed to create a new issue instead of sending email?)

When is a final 3.1.0 release of the spotbugs-maven-plugin expected?

**Comment by vorburger** [comment]
@bshannon I just noticed by coincidence that this seems to have happened day before yesterday, see http://repo1.maven.org/maven2/com/github/spotbugs/spotbugs-maven-plugin/3.1.0/ - perhaps you would like to close this issue now?
