### ISSUE TITLE
Plugin For BlueJ IDE

### ISSUE THREAD

**Issue by aloomis85419** [spotbugs/discuss#25]
Hello all,

I am working with a team of students and we want to bring SpotBugs as a plugin to BlueJ. In order to do this the plugin must be contained in a single Jar file. Is this currently possible with the current version of SpotBugs?

Aaron C. Loomis

**Comment by KengoTODA** [comment]
No, BlueJ support is removed to make project easy to maintain.

https://github.com/spotbugs/spotbugs/blob/be024fea25b26cecdd2688598b8117ecf3c4a120/CHANGELOG.md#removed-3

**Comment by mkienenb** [comment]
Aaron,
Could you repackage multiple jars into a single jar?   Or is there more to
it than that?

**Comment by KengoTODA** [comment]
Sorry I misunderstood context.

It's technically possible, search about "fatjar" or "repackage". However when you redistribute SpotBugs you need to follow it's License (LGPL), please be careful.

**Comment by aloomis85419** [comment]
Hello,

I guess what I meant to ask is there a version of Spotbugs that I could
run/build a jar using Ant? I read the instructions in the manual for the
ant task and it says there should already be a Jar available. The anttask
Jar or something like that. Maybe you guys could explain the ant task to me
so I can explain it to my team later, if you don't mind ?

Thanks!

Aaron C. Loomis

**Comment by KengoTODA** [comment]
Here is document regarding how to run SpotBugs by Ant.
http://spotbugs.readthedocs.io/en/stable/ant.html

**Comment by KengoTODA** [comment]
Recently no discussion on this issue, I'll close.
