### ISSUE TITLE
Moving sonar-findbugs

### ISSUE THREAD

**Issue by h3xstream** [spotbugs/discuss#26]
I recently asked admin permission for https://github.com/h3xstream/sonar-findbugs.
The sonar team transfer me the repository ownership. It used to be a project maintain by SonarSource team.

I was thinking about moving it under the organisation **spotbugs**.

Note : SonarQube provide a free community platform to use SpotBugs. It also provide commercial support and services.

Btw, I will soon do a proper release of the plugin.

**Comment by henrik242** [comment]
Sounds like a good idea!

**Comment by h3xstream** [comment]
No objection.

Moving.. https://github.com/spotbugs/sonar-findbugs

**Comment by h3xstream** [comment]
I lost the admin capabilities of the repo. If anybody from the @spotbugs/admins could restore it. 😄

**Comment by iloveeclipse** [comment]
You have them now.
