### ISSUE TITLE
Migrating from FindBugs, getting missing classes

### ISSUE THREAD

**Issue by rhwood** [spotbugs/discuss#29]
I am migrating an ant project from FindBugs to SpotBugs, and am getting the following output difference:

FindBugs:
```
findbugs:
 [findbugs] Executing findbugs FindBugsTask from ant task
 [findbugs] Running FindBugs...
 [findbugs] Warnings generated: 727
 [findbugs] Calculating exit code...
 [findbugs] Setting 'bugs found' flag (1)
 [findbugs] Exit code set to: 1
 [findbugs] Java Result: 1
 [findbugs] Output saved to /Users/rhwood/Developer/JMRI/JMRI/rhwood/findbugs/findbugs.html
```

SpotBugs:
```
spotbugs:
 [spotbugs] Executing SpotBugs FindBugsTask from ant task
 [spotbugs] Running SpotBugs...
 [spotbugs] The following classes needed for analysis were missing:
 [spotbugs]   itemStateChanged
 [spotbugs]   actionPerformed
 [spotbugs] Warnings generated: 742
 [spotbugs] Missing classes: 2
 [spotbugs] Calculating exit code...
 [spotbugs] Setting 'missing class' flag (2)
 [spotbugs] Setting 'bugs found' flag (1)
 [spotbugs] Exit code set to: 3
 [spotbugs] Java Result: 3
 [spotbugs] Classes needed for analysis were missing
 [spotbugs] Output saved to /Users/rhwood/Developer/JMRI/JMRI/rhwood/JMRI/spotbugs.html
```

Those two missing classes are method names, not classes. What should I be looking for to figure out what when wrong?

**Comment by vorburger** [comment]
[spotbugs] Output saved to /Users/rhwood/Developer/JMRI/JMRI/rhwood/JMRI/spotbugs.html

> What should I be looking for to figure out what when wrong?

@rhwood that spotbugs.html output may be a good starting point? :smiling_imp:

**Comment by rhwood** [comment]
That HTML file has nothing about missing classes in it.

**Comment by lqc** [comment]
@rhwood I noticed a similar problem today after enabling ``find-sec-bugs``.  Do you have this plugin? If yes, can you try disabling it and see if you still get those errors ?

**Comment by rhwood** [comment]
I am not using the `find-sec-bugs` plugin. I am using the following annotations:
- `jcip-annotations-1.0.jar`
- `jsr305.jar`
- `spotbugs-annotations-3.1.1.jar`

**Comment by iloveeclipse** [comment]
Could you check the code - I guess you have lambda's where the calls to the itemStateChanged/actionPerformed are implemented.

If you can provide a small reproducible example project containing the ant build file you are using (I guess it is ant output?) and the affected code, we could try to provide a patch.

**Comment by rhwood** [comment]
Some of the code uses lambdas. The source project is at https://github.com/rhwood/JMRI/tree/spotbugs It might take me a couple of days to gin up a small sample project.

**Comment by iloveeclipse** [comment]
I've created https://github.com/spotbugs/spotbugs/issues/527. There is a reproducer and I will try to spent some time on debugging it.
