### ISSUE TITLE
"release-3.1" branch as default for incoming PR's

### ISSUE THREAD

**Issue by iloveeclipse** [spotbugs/discuss#31]
I see that we have some PR's appearing, this is really good!
However, all of those PR's are (by default) created for "master" branch which is targeting 4.0 release.

Most of the PR's coming with a smaller fixes, most of those fixes are perfectly working on 3.1 code, and most of the users want see them in a final 3.1.x release soon.

I don't see 4.0 to be released soon, so it makes more sense people who want to contribute will *by default* use the "right" branch, which is `release-3.1`.

I'm going to make `release-3.1` branch default now, but if someone has any objections - please speak up.

**Comment by vorburger** [comment]
@iloveeclipse sounds like a great plan to me - sooner, faster is good.

I'm assuming _"someone"_ will take care of making sure what goes into `release-3.1` is also on master? :smile:

**Comment by iloveeclipse** [comment]
Sure.

**Comment by KengoTODA** [comment]
Confirmed that currently `release-3.1` is the default branch for spotbugs project. Thanks for someone who made this change!

![screenshot from 2018-01-22 10-03-32](https://user-images.githubusercontent.com/505751/35202107-8648c4b4-ff5b-11e7-9607-94dcfbf0eb2f.png)
