### ISSUE TITLE
Permissions for Sonar cloud / sonar-findbugs-plugin

### ISSUE THREAD

**Issue by h3xstream** [spotbugs/discuss#37]
I need permissions to mark issue to False Positive on the Sonar instance.
https://sonarcloud.io/dashboard?id=com.github.spotbugs%3Asonar-findbugs-plugin

The plugin can't be release without this requirement.

**Comment by KengoTODA** [comment]
I've granted admin role to you, please check.

**Comment by h3xstream** [comment]
Thanks @KengoTODA
