### ISSUE TITLE
Release 3.1.3?

### ISSUE THREAD

**Issue by AustinShalit** [spotbugs/discuss#39]
Taking a look at the current diff (https://github.com/spotbugs/spotbugs/compare/3.1.2...release-3.1) it looks like if a release is pushed, spotbugs will gain partial java 10 support from https://github.com/spotbugs/spotbugs/commit/c2ef7286e05667c74c503998b20392dfde742be6.  Is this true?  How do the maintainers feel about pushing a release?

**Comment by iloveeclipse** [comment]
I'm OK with release, but Java 10 is not on my list so far. I would be happy to use 9.

**Comment by henrik242** [comment]
9 is already EOL.  We use 10 in production where I work, so this is good.

**Comment by iloveeclipse** [comment]
Sure, what I meant: *if* I would be able to update my JRE as soon as it is released I would be happy :-)

Switching JRE is easy (sudo yum install ...), but proper migration of a code base & all the tooling after that is hard. 

From my experience (6->7, 7->8), there are always few issues with changed behavior, "fixed bugs", new bugs in JRE etc in a big codebase. Even such a "trivial" thing like a different hashCode() calculation in HashMaps can cost you weeks.

Regarding 3.1.3: it is underway now, see https://github.com/spotbugs/spotbugs/pull/613.
