### ISSUE TITLE
Execute spotbugs during build instead of site generation?

### ISSUE THREAD

**Issue by mackpenn** [spotbugs/discuss#43]
Hello! I would like to know if there is a way to make spotbugs execute during the build as well as during site generation? Right now, when I run "mvn site" a report generates just fine. However, when I run "mvn clean site" the report disappears (the rest of my reports remain, however). In order to get the Spotbugs report back, I have to run "mvn test" then "mvn site" again. Is there a way around this, and if not, do you mind explaining why this happens? I am new to maven, using maven 3.3 and spotbugs 3.1.3!

**Comment by KengoTODA** [comment]
> when I run "mvn clean site" the report disappears 

This is because SpotBugs need .class files to analyse, but `clean` phase deletes them.
To solve this problem, I hope "mvn clean compile site" can be the solution.

> Execute spotbugs during build instead of site generation? #43

This is also possible, add `spotbugs-maven-plugin` under `project.build.plugins` in your `pom.xml`, then `mvn verify` will run [check goal of spotbugs-maven-plugin](https://spotbugs.github.io/spotbugs-maven-plugin/check-mojo.html).

```xml
<project>
  <build>
    <plugins>
      <plugin>
        <groupId>com.github.spotbugs</groupId>
        <artifactId>spotbugs-maven-plugin</artifactId>
        <version>3.1.3.1</version>
      </plugin>
      ...
    </plugins>
    ...
  </build>
  ...
</project>
```

**Comment by meredrica** [comment]
putting it under project.build.plugins doesn't do anything with version 4.0.4 or 4.0.3

**Comment by jwgmeligmeyling** [comment]
If you want to include the report in `mvn site`, the plugin has to be configured under `<reporting>`, not `<build>`. If you put it under build, without any execution, Spotbugs has to be invoked manually using the Maven goal: `mvn spotbugs:spotbugs`

**Comment by KengoTODA** [comment]
I'll close this inactive issue. Please repost a new one if necessary.
