### ISSUE TITLE
Travis CI failure: 3.1.6 SNAPSHOT is not published

### ISSUE THREAD

**Issue by mmoayyed** [spotbugs/discuss#47]
I am reviewing https://travis-ci.org/spotbugs/spotbugs/builds/396638921 which seems to be the [latest build job](https://travis-ci.org/spotbugs/spotbugs/requests) publishing snapshots for 3.1. The build was not able to publish and upload snapshots due to some connectivity issue. Could this job be restarted?

3.1.6 SNAPSHOT seems to have updated asm versions to 6.2 which may allow support for JDK 11. (Experimenting with this build/version over at https://github.com/apereo/cas)

PS It would also be very good if the milestones could be updated to indicate the release schedule and tentative dates for 3.1.6 and beyond.

**Comment by KengoTODA** [comment]
YES, 3.1.5. Sorry!
