### ISSUE TITLE
RFC: Which blog service you're watching?

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/discuss#48]
I'm personally going to post SpotBugs related blog articles, and searching good service that is famous even for Java/JVM developers. Current options:

* https://dev.to/ - Smaller but active, and [famous for server-side engineers](https://dev.to/ben/making-devto-insanely-fast) I believe
* https://medium.com/ - Really famous and active, but inaccessible from inside of GFW
* https://boostlog.io/ - Small and less Java related posts

If you have more suggestions, please let me know. Thanks!

**Comment by iloveeclipse** [comment]
I must be too old school - I like http://www.javaperformancetuning.com/newsletter.shtml

**Comment by KengoTODA** [comment]
https://dev.to/kengotoda
I've started to post at dev.to.
