### ISSUE TITLE
Create for ISSUE_TEMPLATE.md spotbugs project(s)

### ISSUE THREAD

**Issue by h3xstream** [spotbugs/discuss#50]
Many open-source projects encourage their users to ask questions on StackOverflow instead of Github issues.

SpotBugs projects could link to StackOverflow with the appropriate tags: https://stackoverflow.com/questions/ask?tags=spotbugs,java

I just created an ISSUE_TEMPLATE.md file for the find-sec-bugs:
https://github.com/find-sec-bugs/find-sec-bugs/issues/new

**Comment by vorburger** [comment]
perhaps just open a PR with the ISSUE_TEMPLATE.md you would propose for this project?

**Comment by h3xstream** [comment]
Good point. I was not expecting a big discussion anyway.
https://github.com/spotbugs/spotbugs/pull/730
