### ISSUE TITLE
Help with spotbugs-gradle-plugin maintenance

### ISSUE THREAD

**Issue by chali** [spotbugs/discuss#53]
Hello, Spotbugs maintainers,

Can I offer some help with maintenance of spotbugs-gradle-plugin. I spend quite a time with Gradle plugins over here https://github.com/nebula-plugins. I would love to help especially with compatibility with future Gradle versions. What could I do to get the maintainer access?

Thanks for consideration
Martin

**Comment by henrik242** [comment]
Hi @chali! All help is greatly appreciated! I suggest that you start by submitting some pull requests in areas you feel need improvement. Looking forward to your contributions 👍

**Comment by chali** [comment]
Thank you @henrik242 They are there :-) Do you think I could get the maintainer rights to get those changes merged more quickly?

**Comment by baron1405** [comment]
@henrik242 The spotbugs-gradle-plugin cannot be used with the latest release of Gradle (4.10). @chali has a reviewed, simple PR but for unknown reasons, the maintainer @KengoTODA has not responded to the PR, open issue or direct emails. This has lead to Gradle upgrades being delayed and Spotbugs being (temporarily) removed from projects. On behalf of a growing number of concerned Spotbugs users, please grant @chali maintainer rights to the spotbugs-gradle-plugin project.

**Comment by baron1405** [comment]
@henrik242 The situation with the spotbugs-gradle-plugin has gotten worse to the point where the project may need to be forked. Thought the maintainer finally merged the PR, he did not generate a release. Despite numerous requests from users to generate a release, there has been no response of any kind from the maintainer. Even after being asked to add @chali as a maintainer to help out with a release, there has been no response. We all would hate to see a fork of the plugin project so if there is anything you can do to help avoid this, it would be very appreciated.

**Comment by henrik242** [comment]
@baron1405 Sorry, I lack the relevant permissions to do anything.  But @KengoTODA has opened a PR, so things are hopefully getting somewhere: https://github.com/spotbugs/spotbugs-gradle-plugin/pull/48
