### ISSUE TITLE
License of SpotBugs logos

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/discuss#6]
I found that we have no page which describes license of SpotBugs logos.
License will help community to spread SpotBugs, so let's decide license and make a page to announce it.

I think that [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) is suitable, how do you think? 

logos:
- https://github.com/spotbugs/spotbugs.github.io/tree/master/images/logos
- https://github.com/spotbugs/spotbugs.github.io/blob/master/spotbugs-icon.png

refs:
- https://github.com/spotbugs/spotbugs/issues/36
- https://eclipse.org/artwork/
- https://wiki.jenkins.io/display/JENKINS/Logo
- https://www.docker.com/brand-guidelines
- https://github.com/logos

**Comment by iloveeclipse** [comment]
Good idea, +1 from me.

**Comment by sewe** [comment]
CC BY-SA 4.0 sounds *OK*, but I can imagine dropping the SA (share alike). Consider a third-party SpotBugs plugin that wants to use the SpotBugs logo in its documentation. AFAIK, this would require it to publish its documentation under CC BY-SA 4.0 as well (but IANAL).

Wouldn’t CC BY 4.0 be sufficient for our purposes?

**Comment by KengoTODA** [comment]
I think CC BY is also OK too.
