### ISSUE TITLE
spotbugs-maven-plugin 3.1.8 not yet released?

### ISSUE THREAD

**Issue by davewichers** [spotbugs/discuss#60]
Per https://search.maven.org/search?q=g:com.github.spotbugs - everything is basically 3.1.8 except for this one, which is still at 3.1.7. Can you release the 3.1.8 version so maven can easily be used to use the latest spotbugs engine?

**Comment by KengoTODA** [comment]
it has been released, plz refer:

https://github.com/spotbugs/spotbugs-maven-plugin/releases/tag/spotbugs-maven-plugin-3.1.8
