### ISSUE TITLE
When we stop 3.1.x release?

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/discuss#62]
Currently spotbugs has two branches: master for 4.x and release-3.1 for 3.1.x.
Here I want to discuss when we stop 3.1 release to focus on improvement.

We're providing 3.1.x release to support backward-compatible solution for FindBugs users. I think it
is necessary to support long-aged Java projects.
However, it also makes bugfix and improvement difficult; for instance https://github.com/spotbugs/spotbugs/issues/28 is not closed even though we spent two years.

[The next January is EOL for Java SE 8](https://blogs.oracle.com/java-platform-group/end-of-public-updates-is-a-process%2c-not-an-event), so I think it's nice timing to ask long-aged Java projects to migrate to newer solution. Let's consider to release 3.1.12 at the next January, and make it the last release except for vulnerability fix.

Note that we have different issue #17 to discuss about what we do in 4.0 release.

**Comment by KengoTODA** [comment]
Hi @spotbugs/everyone, do you have your opinion about this topic? :)

**Comment by henrik242** [comment]
I think the main focus should be 4.x on jdk11. I haven't done anything on jdk8 for almost a year.

**Comment by ThrawnCA** [comment]
4.x on JDK 11 makes sense. Anyone sticking to JDK 8 is likely dealing with legacy issues of some kind, and so is less likely to be able to make use of the latest and greatest bug detector.

**Comment by KengoTODA** [comment]
I'll keep this topic open to discuss for one week later. At Dec/26, if no contributor against, we'll stop 3.1.x release from the next Feb.

**Comment by KengoTODA** [comment]
@spotbugs/everyone Today is the deadline to collect your opinion, please post if you have any other opinion :)

**Comment by KengoTODA** [comment]
I'll close this issue. Let's make 3.1.11 and 3.1.12 stable, then focus on 4.0 development later. Thank you!
