### ISSUE TITLE
Alternative to LGPL-licensed `@SuppressFBWarnings` annotation?

### ISSUE THREAD

**Issue by fcurts** [spotbugs/discuss#64]
`com.github.spotbugs:spotbugs-annotations:3.1.10` is LGPL licensed, which means I can't use it in my Apache 2 licensed software. Are there any alternatives, such as defining my own annotation recognized by SpotBugs? It would be a pity if I had to list every warning identified as false positive in a suppression file.

**Comment by fcurts** [comment]
@iloveeclipse thanks! works great and is immensely useful. didn't find this information when searching docs/web.

**Comment by iloveeclipse** [comment]
*code* is the docs :-)

**Comment by fcurts** [comment]
@KengoTODA That's the standard solution I had used so far, but it's not clear to me what the licensing implications are, and I'd rather not spend my time arguing with lawyers over this.

Would be nice to see spotbugs-annotations relicensed under a more permissive license.

**Comment by KengoTODA** [comment]
We're not copyright holder so we cannot change OSS license of this product.
We may consider to make a new annotations from scratch, but it's not listed in [roadmap](https://github.com/spotbugs/discuss/issues/17) for now.
