### ISSUE TITLE
RFC: Which feature in SpotBugs core you're actively using?

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/discuss#65]
We're going to switch from developing 3.1 to 4.0 from the next month. And in this major version up, I want to consider to drop several features that isn't so used in community, to make our project easy to hack and maintain.

I will list features that is not so major in my personal understanding. Please vote for active feature in your usage. I will keep actively voted features even in 4.0.

## Target Features

* [scripts](https://github.com/spotbugs/spotbugs/tree/release-3.1/spotbugs/src/scripts) that is not used so widely.
* [Bug rank](https://stackoverflow.com/a/46308682/814928) that is optional and not so used widely in my understanding (each project has their priority, so it's better to handle 'rank' outside of SpotBugs like SonarQube)
* [Priority/Confidence](https://stackoverflow.com/a/15116885/814928), by the same reason with bug rank
* 'speed' attribute in findbugs.xml
* [SQL](https://github.com/spotbugs/spotbugs/tree/release-3.1/spotbugs/src/sql)
* [JNLP](https://github.com/spotbugs/spotbugs/tree/release-3.1/spotbugs/jnlp) for outdated Java Web Start

## Vote

[![](https://api.gh-polls.com/poll/01D2B6035C4TWXSJP20XHWAVWQ/script)](https://api.gh-polls.com/poll/01D2B6035C4TWXSJP20XHWAVWQ/script/vote)
[![](https://api.gh-polls.com/poll/01D2B6035C4TWXSJP20XHWAVWQ/bug%20rank)](https://api.gh-polls.com/poll/01D2B6035C4TWXSJP20XHWAVWQ/bug%20rank/vote)
[![](https://api.gh-polls.com/poll/01D2B6219HGJYZG4VRSFPG4G6K/priority%20and%20confidence)](https://api.gh-polls.com/poll/01D2B6219HGJYZG4VRSFPG4G6K/priority%20and%20confidence/vote)
[![](https://api.gh-polls.com/poll/01D2B6035C4TWXSJP20XHWAVWQ/speed%20attribute)](https://api.gh-polls.com/poll/01D2B6035C4TWXSJP20XHWAVWQ/speed%20attribute/vote)
[![](https://api.gh-polls.com/poll/01D2B6035C4TWXSJP20XHWAVWQ/SQL)](https://api.gh-polls.com/poll/01D2B6035C4TWXSJP20XHWAVWQ/SQL/vote)
[![](https://api.gh-polls.com/poll/01D2B6035C4TWXSJP20XHWAVWQ/JNLP)](https://api.gh-polls.com/poll/01D2B6035C4TWXSJP20XHWAVWQ/JNLP/vote)

**Comment by iloveeclipse** [comment]
Any clue *how* to vote?

**Comment by KengoTODA** [comment]
To vote, click bar in the post. Here is example: https://github.com/apex/gh-polls

**Comment by iloveeclipse** [comment]
And again, if you remove Bug Rank, Proirity and Confidence, you will not be able to use SpotBugs without SonarQube, so you will break Eclipse plugin and tools using xml output (so command line which generates html reports).

**Comment by KengoTODA** [comment]
Yes so we need to update Eclipse plugin side too. Let's do so if and only if these features are not used by users. :)

**Comment by iloveeclipse** [comment]
Sorry, I didn't get it. You propose to remove rank, confidence and priority - so how users are supposed to differentiate various bugs then? *Another* one metric?

**Comment by iloveeclipse** [comment]
Is there any reason why script and bug rank bars show 50% but confidence 100%, but all three have ea h one vote? Schouldn't the bars show same value?

**Comment by KengoTODA** [comment]
wmm, maybe it's problem caused by my process to make these polls. Only 'confidence and priority' is handled as individual polls so it's always 100%.

There are already multiple vote, so plz kindly let me keep current situation. I'll remember that bar chart of this item isn't intuitive.

**Comment by mkienenb** [comment]
Something to keep in mind.

If you are starting with a clean slate, you might not find rank important, but if you are applying spotbugs to an existing project for the first time, the output will be overwhelming.   Rank gives people guidance which items need to be handled first.

Once everything is fixed, or if you are starting a new project, rank isn't as important.

**Comment by h3xstream** [comment]
I clicked on priority and confidence. It was not clear if it was for the removal or for keeping the feature.

**Comment by KengoTODA** [comment]
@h3xstream keeping. please vote on feature that you are using. Sorry for this confusion :<

**Comment by KengoTODA** [comment]
@mkienenb yes I know, but most legacy projects don't need latest feature of SpotBugs, they just need 'bug fixed FindBugs' then 3.1.x should be enough. :)

**Comment by ksnortum** [comment]
+1

Thank you for expressing this in a way I  never could.  The more a first
time user gets alienated, the harder it is to expand the reach of the
product.

-- 
Knute Snortum

**Comment by aaime** [comment]
I just added SpotBugs in the mix in a very old project, and single handedly started fixing issues. I started by fixing only rank 1, and bit by bit went up to rank 10 (mind, using build checks and having the build fail, without a build failure nobody else would have cared). Without a way organize reports by some sort of priority, I would not have been able to start (and indeed, I tried spotbugs first, was reporting too many things and could not figure out how to configure it, so I've integrated errorprone and pmd first, and only later added spotbugs to the mix too).

**Comment by KengoTODA** [comment]
Hello all,

Thanks for your feedback! Now I'm sure that some features are actively used. I'm little bit surprised that sql and jnlp also have users, but at least its usage isn't so high comparing than others:

![which feature in spotbugs core you re actively using_](https://user-images.githubusercontent.com/505751/53706895-719a4500-3e67-11e9-9193-5474402190a1.png)

I'm going to propose deprecating sql, jnlp and speed attribute. I won't touch others that has much users. :)
