### ISSUE TITLE
IntelliJ plugin

### ISSUE THREAD

**Issue by jdauzat** [spotbugs/discuss#73]
Hi, my team would like to upgrade from FindBugs to SpotBugs, but most of us use IntelliJ. Is there an intelliJ plugin in the works?

**Comment by lasselindqvist** [comment]
The most sense would probably make forking https://github.com/andrepdo/findbugs-idea preferably in cooperation with @andrepdo or/and @retomerz which is the main contributor to that. The license for that is LGPL (https://github.com/andrepdo/findbugs-idea/blob/master/src/LICENSE.txt)

**Comment by KengoTODA** [comment]
refs https://github.com/spotbugs/spotbugs/issues/515

**Comment by KengoTODA** [comment]
SpotBugs IntelliJ Plugin has already been released at:
https://plugins.jetbrains.com/plugin/14014-spotbugs
