### ISSUE TITLE
Benchmarks used to evaluate FindBugs

### ISSUE THREAD

**Issue by DhritiKhanna** [spotbugs/discuss#84]
Hello developers,
The paper titled "Finding Concurrency Bugs in Java" used certain benchmarks to evaluate FindBugs. The source code does not come with those benchmarks I think. I will be highly thankful if you can provide the set of those subjects to me.

**Comment by KengoTODA** [comment]
Could you contact with the author directly? In SpotBugs team we have no author in my understanding.
