### ISSUE TITLE
spotbugs always returns 0

### ISSUE THREAD

**Issue by tosiara** [spotbugs/discuss#89]
Hi,

Is there a way to get non-zero return value in case issues found?

I'm running like this:
```
SPOTBUGS_HOME=~/lib/spotbugs-4.0.0 spotbugs -textui -medium .
```
`$?` always shows return value is 0

**Comment by KengoTODA** [comment]
use `-exitcode` option :)

https://spotbugs.readthedocs.io/en/stable/running.html#project-configuration-options

**Comment by tosiara** [comment]
As far as I can see this option overrides the `zero `and spotbugs will always return the value you provide.

But I'd like to get `zero` if no findings, and `non-zero` if there were findings. Like pretty much all security code scans do. Is this possible?

**Comment by tosiara** [comment]
Ah sorry, miss-read the docs. This option takes no value
Looks like this is what I was looking for
Thanks
