### ISSUE TITLE
How to Use SpotBugs in Github Pull requests ? 

### ISSUE THREAD

**Issue by PradeepShetty14** [spotbugs/discuss#91]
Is there a plugin which can be integrated with github ?

**Comment by lasselindqvist** [comment]
That depends on your CI system and needs. For example Jenkins has a plugin for publishing the results from Spotbugs. Spotbugs itself doesn't provide such things.

**Comment by PradeepShetty14** [comment]
We want to integrate the spotbugs to the git hub PR process, Idea is to examine the code before the code is committed to the master branch.  Is there a way we can develop a plugin for this? or is there any limitation?

**Comment by lasselindqvist** [comment]
That depends on your build system. One way is to use the Maven plugin for Spotbugs to fail the build on errors (https://spotbugs.github.io/spotbugs-maven-plugin/check-mojo.html#failOnError).

**Comment by PradeepShetty14** [comment]
Sure, we deal with java and maven, will explore on this.

**Comment by PradeepShetty14** [comment]
Thanks it worked using the below command
mvn clean install spotbugs:check -Dspotbugs.failOnError=True
