### ISSUE TITLE
Produce SpotBugs results in SARIF v2.1.0 format

### ISSUE THREAD

**Issue by lgolding** [spotbugs/discuss#95]
Now that [SARIF v2.1.0](https://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.pdf) is an OASIS Standard, there's an internal Microsoft initiative to integrate SpotBugs into our SARIF-driven static analysis ecosystem. We'd like to do it in a way that benefits the entire community.

@michaelcfanning and I (@lgolding) are the co-editors of the SARIF specification, and we're happy to help in whatever way you think is most appropriate. We've integrated SARIF into open source tools such as [Cake](https://github.com/cake-contrib/Cake.Issues.Reporting.Sarif) and [ESLint](https://www.npmjs.com/package/@microsoft/eslint-formatter-sarif), as well as Microsoft tools such as the C++, C#, and VB compilers.

There are various approaches to adding SARIF support:

- Integrate SARIF production directly into SpotBugs as an output format, alongside your existing XML, HTML, emacs, and xdoc formats.

- Provide an open source "SARIF converter" that would plug into the existing "SARIF MultiTool". We have taken this approach with other tools; for example, with the [Fortify FPR converter](https://github.com/microsoft/sarif-sdk/blob/master/src/Sarif.Converters/FortifyFprConverter.cs).

- If SpotBug supported a plugin mechanism for output formats as it does for analysis rules, a SARIF emitter could plug into it.

In addition to enabling SpotBugs to participate in SARIF-driven ecosystems, SARIF output could alleviate certain issues in the SpotBugs XML output format:

- As mentioned in [spotbugs/discuss/#69](https://github.com/spotbugs/discuss/issues/69), the XML format has trouble representing multiple code flows that share a common set of locations. SARIF has explicit support for that scenario: a result can contain multiple code flows, and the code locations can be shared among the code flows (or not, on a per-location basis).

- The `BugInstance` sub-element that specifies the location of the bug varies, depending on the `BugInstance`'s `type`. SARIF would provide a uniform representation for all results (because its `result` object has a `locations` property that is explicitly seprarate from its `codeFlows` property).

**Comment by KengoTODA** [comment]
At this moment, the report generation process isn't pluggable. A workaround is that you generate your report from XML report that is parser-friendly. 

It's technically possible to make this process pluggable, but it's stateful now so it needs some time.

**Comment by lgolding** [comment]
What do you think about the direct export option? We can continue to explore the XML->SARIF option but it has some complications (described [above](https://github.com/spotbugs/discuss/issues/95#issue-642019647)). Also, by the way, GitHub's [automatic code scanning](https://help.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code) will [accept direct export from tools that produce SARIF 2.1.0](https://help.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/sarif-support-for-code-scanning), so there would be a tangible benefit to SpotBugs in supporting it.

**Comment by KengoTODA** [comment]
It sounds awesome. And it should be technically possible to implement the direct export option.

I'm not sure about this format, and probably have no time to handle, so I hope that other contributors will have a try.

**Comment by uhafner** [comment]
This would be really helpful to have a different format since parsing of the current format is a complicate task. (And using the internal parser is also not very elegant since the whole SpotBugs library is required as a dependency). 

On the other hand, is there a Java parser for SARIF already available? In my role as author of the Jenkins warnings plugin I am a consumer of the current SpotBugs format. So exporting the bugs to a new format is only half the way, we then need also the way back from the XML file to the object model of the bugs. Is there anything planned here on the SARIF side?

**Comment by lgolding** [comment]
We currently have .NET and TypeScript language bindings for the SARIF object model. We don't yet have a Java binding. The .NET binding is actually generated programatically from the [SARIF JSON schema](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/schemas/sarif-schema-2.1.0.json). If there is a JSON-schema-to-Java-OM utility around, you would get the bindings for free. Do you know of one? I didn't find one in a quick search just now.

**Comment by lgolding** [comment]
@uhafner, by the way, if your [Jenkins warning plugin](https://plugins.jenkins.io/warnings-ng/) consumed SARIF, you would automatically have support for any tool that produces that standard format. This sounds like another great opportunity. We can talk about it over on your repo if you'd like.

@michaelcfanning FYI.

**Comment by michaelcfanning** [comment]
I believe that @lcartey of CodeQL has produced a Java OM from the SARIF schema.

**Comment by uhafner** [comment]
I see. The schema looks quite complex. The tools that normally show up in the warnings plugin typically produce a list of warnings with a couple of properties only. Are there a lot of tools using SARIF already?

**Comment by michaelcfanning** [comment]
It's a complex format, intended to cover the range of static analysis tools out there. You might find the [SARIF Tutorial](https://github.com/microsoft/sarif-tutorials) a little friendlier for ramping up. We have a well-developed C# [SARIF-SDK](https://github.com/microsoft/sarif-sdk) to facilitate read/write, other scenarios but that isn't helpful for Java, of course.

Internally at Microsoft, every tool that's run as part of security/other policy has SARIF support. Every tool owned internally or for which a Microsoft engineer serves as open source coordinator (such as [BinSkim](https://github.com/microsoft/binskim) exports the format directly, Both of Microsoft's publicly shipping analysis platforms (PREfast and Roslyn) have direct support.

Externally, there's support for ESLint, CLang analyzer (built-in). GrammaTech supports the format, as does Semmle/CodeQL and MicroFocus Fortify is working on it (I believe). We have open source converters for Fortify and Contrast Security.

The discussion was actually prompted by Microsoft utilization of SpotBugs as Larry mentioned. All our engineering systems for producing results, filing work items, etc., are driven by the format, so we're looking for some sort of SARIF solution so that we can get SpotBugs plugged in.

@lgolding and I are both happy to help advise on SARIF support. If it's helpful, we could attempt a contribution for this. If direct support in SpotBugs looks too intimidating to take on, I think Microsoft will fund authoring an open source converter from SpotBugs XML.

**Comment by KengoTODA** [comment]
note: Following files are key factors to generate spotbugs report. Not sure they provide enough feature to generate in the SARIF format.
* [BugInstance](https://github.com/spotbugs/spotbugs/blob/55eaedb042b672b4c3fd16b5515ba0a4dfc2124b/spotbugs/src/main/java/edu/umd/cs/findbugs/BugInstance.java) is the class representing detected bug
* [BugReporter](https://github.com/spotbugs/spotbugs/blob/55eaedb042b672b4c3fd16b5515ba0a4dfc2124b/spotbugs/src/main/java/edu/umd/cs/findbugs/BugReporter.java) is the interface to generate reports
* [TextUIBugReporter](https://github.com/spotbugs/spotbugs/blob/55eaedb042b672b4c3fd16b5515ba0a4dfc2124b/spotbugs/src/main/java/edu/umd/cs/findbugs/TextUIBugReporter.java) is an implementation providing useful features

**Comment by KengoTODA** [comment]
I'll check [sarif-tutorials](https://github.com/microsoft/sarif-tutorials) later. Thanks for your share!

**Comment by KengoTODA** [comment]
I'm working on this issue. I cannot find a good way to generate Java binding from JSON schema, so writing it on the top of [the `org.json:json` library](https://github.com/stleary/JSON-java).

https://github.com/spotbugs/spotbugs/compare/sarif-report

**Comment by lgolding** [comment]
I'm glad you're working on this! I'm happy to video conference with you to discuss the details of how to map your internal bug representation to SARIF. We can start simple, and then there are many ways to produce SARIF output that's effective for end users. In fact I'm writing a document about that now, which I'll share with you very soon.

**Comment by KengoTODA** [comment]
Thank you, Current my idea is that:

* Map data in `findbugs.xml` and `messages.xml` to [`rule metadata`](https://github.com/microsoft/sarif-tutorials/blob/025ac9ef475691969dd822ca5ce681b9ea99cef8/docs/Authoring-rule-metadata-and-result-messages.md#categories-tags). Switch `messages.xml` to decide which language (en, ja, or fr) we use to report.
* Use bug pattern's type (e.g. [`OBL_UNSATISFIED_OBLIGATION`](https://github.com/spotbugs/spotbugs/blob/55eaedb042b672b4c3fd16b5515ba0a4dfc2124b/spotbugs/etc/messages.xml#L8118)) as [`identifier` defined in SARIF](https://github.com/microsoft/sarif-tutorials/blob/025ac9ef475691969dd822ca5ce681b9ea99cef8/docs/Authoring-rule-metadata-and-result-messages.md#stable-opaque-identifier). It's also used as [`name`](https://github.com/microsoft/sarif-tutorials/blob/025ac9ef475691969dd822ca5ce681b9ea99cef8/docs/Authoring-rule-metadata-and-result-messages.md#human-readable-identifier).
* Use `ShortDescription` (see [example](https://github.com/spotbugs/spotbugs/blob/55eaedb042b672b4c3fd16b5515ba0a4dfc2124b/spotbugs/etc/messages.xml#L8119)) as [`shortDescription`](https://github.com/microsoft/sarif-tutorials/blob/025ac9ef475691969dd822ca5ce681b9ea99cef8/docs/Authoring-rule-metadata-and-result-messages.md#short-description).
* Use `LongDescription` that possibly including substitution sequences (see [example](https://github.com/spotbugs/spotbugs/blob/55eaedb042b672b4c3fd16b5515ba0a4dfc2124b/spotbugs/etc/messages.xml#L1662)) as [`messageStrings.default`](https://github.com/microsoft/sarif-tutorials/blob/025ac9ef475691969dd822ca5ce681b9ea99cef8/docs/Authoring-rule-metadata-and-result-messages.md#message-strings).
* Use BugCategory (see [example](https://github.com/spotbugs/spotbugs/blob/55eaedb042b672b4c3fd16b5515ba0a4dfc2124b/spotbugs/etc/messages.xml#L93)) as [`categories`](https://github.com/microsoft/sarif-tutorials/blob/025ac9ef475691969dd822ca5ce681b9ea99cef8/docs/Authoring-rule-metadata-and-result-messages.md#categories-tags)

And here is known issues:

* Need discussion about how to map [SpotBugs' priority](https://github.com/spotbugs/spotbugs/blob/3883a7b750fb339577be073bc45e36b6f268777b/spotbugs/src/main/java/edu/umd/cs/findbugs/Priorities.java) to [`Level`](https://github.com/microsoft/sarif-tutorials/blob/025ac9ef475691969dd822ca5ce681b9ea99cef8/docs/Authoring-rule-metadata-and-result-messages.md#level).
* SpotBugs' detailed descriptions for bug pattern are written in HTML, see [example](https://github.com/spotbugs/spotbugs/blob/55eaedb042b672b4c3fd16b5515ba0a4dfc2124b/spotbugs/etc/messages.xml#L8088-L8116). We need to convert it to plain text or markdown, to use it as [`fullDescription`](https://github.com/microsoft/sarif-tutorials/blob/025ac9ef475691969dd822ca5ce681b9ea99cef8/docs/Authoring-rule-metadata-and-result-messages.md#full-description).
* By default SpotBugs' bug pattern has no URL property. For default detectors we can use `spotbugs.readthedocs.io/en/stable/bugDescriptions.html#${BUG_PATTERN_TYPE}` but for plugins we have no way to provide. 

I will list more my doubt/questions later.

**Comment by lcartey** [comment]
@KengoTODA Sorry for not responding sooner, but I have had some success with:

http://www.jsonschema2pojo.org/

For generating a Java object model for SARIF. They also provide Maven/Gradle/Ant plugins for automating the process.

**Comment by KengoTODA** [comment]
SpotBugs 4.1.0 provides an experimental support for the SARIF 2.1.0. The generated report can pass the latest SARIF validator.

It should have known and unknown issues (e.g. https://github.com/spotbugs/spotbugs/pull/1221), please feel free to issue at https://github.com/spotbugs/spotbugs/issues

**Comment by yongyan-gh** [comment]
> @KengoTODA Sorry for not responding sooner, but I have had some success with:
> 
> http://www.jsonschema2pojo.org/
> 
> For generating a Java object model for SARIF. They also provide Maven/Gradle/Ant plugins for automating the process.

Hi @lcartey , have you ever successfully generated POJO classes from Sarif Json schema. 
KengoTODA faced some [issue](https://github.com/eirnym/js2p-gradle/issues/10) in generating AdditionalProperties. 
The [jsonschema2pojo](https://github.com/joelittlejohn/jsonschema2pojo) may not have a full coverage of Json schema specs.
