### ISSUE TITLE
How can I use your code?

### ISSUE THREAD

**Issue by leila-you** [spotbugs/discuss#97]
Hi.
I want to use your code in my project but I can not execute the code in eclipse and I can not find the main class for testing java code. I want to use this code for my java project. please help me to run this code.
thanks.

**Comment by KengoTODA** [comment]
[edu.umd.cs.findbugs.LaunchAppropriateUI](https://github.com/spotbugs/spotbugs/blob/60f5ffd298327078e8425ffd2b76d0b2242583d5/spotbugs/src/main/java/edu/umd/cs/findbugs/LaunchAppropriateUI.java) is the main class described in the `MANIFEST.MF` file. [FindBugs](https://github.com/spotbugs/spotbugs/blob/60f5ffd298327078e8425ffd2b76d0b2242583d5/spotbugs/src/main/java/edu/umd/cs/findbugs/FindBugs.java) and [FindBugs2](https://github.com/spotbugs/spotbugs/blob/60f5ffd298327078e8425ffd2b76d0b2242583d5/spotbugs/src/main/java/edu/umd/cs/findbugs/FindBugs2.java) are also important classes to run SpotBugs.

BTW if you're running SpotBugs by the Eclipse plugin, you may refer [the official Eclipse Plugin manual](https://spotbugs.readthedocs.io/en/stable/eclipse.html).

**Comment by KengoTODA** [comment]
I'll close this inactive issue. Please repost a new one if necessary.
